[package]
name = "ebi-proto"
version = "0.1.0"
edition = "2024"

[dependencies]
enum_dispatch = "0.3.13"
paste = "1.0.15"
prost = "0.13"
prost-types = "0.13"
bytes = "1.10.1"

[build-dependencies]
prost-build = { version = "0.13" }
